name: Deploy All Projects to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: 
          - 'Counter App'
          - 'Grade Calculator'
          - 'Number Comparator App'
          - 'Multiplication Table'
          - 'Number Table'
          - 'Render Products'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        working-directory: ./${{ matrix.project }}

      - name: Build project
        run: npm run build
        working-directory: ./${{ matrix.project }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ matrix.project }}/dist
          destination_dir: ${{ matrix.project }}
  deploy-index:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Deploy Index Page
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./